Completely remove hard source webpack plugin
When running **several times in a row**(*) `make test`, this webpack plugins appears to provoke the following errors:
```
14 11 2017 10:02:33.987:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
14 11 2017 10:02:33.989:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
14 11 2017 10:02:34.006:INFO [launcher]: Starting browser ChromeHeadless
14 11 2017 10:02:34.320:INFO [HeadlessChrome 0.0.0 (Linux 0.0.0)]: Connected on socket 7cfdxPIj-lVaIP5OAAAA with id 80989099
HeadlessChrome 0.0.0 (Linux 0.0.0) ERROR
 Script error.
```
or
```
    ✖ loadFileList
      HeadlessChrome 0.0.0 (Linux 0.0.0)

    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```
(*) These errors disappear when clearing module's cache: `rm -rf node_modules/.cache/hard-source/`. Once they reappear, they "stay".

Considering the small speed improvement it provides (https://github.com/Polyconseil/systematic/pull/67 stated 2s, which is the order of magnitude I noticed on my project) and the numerous issues it can cause (see https://github.com/mzgoddard/hard-source-webpack-plugin/issues) remove it.